[programs.localnet]
gyc_sol_swap = "91cSWaofsRKHtbLM93Qdg2ELMnSaqPzMhk1wu1Jaxpvb"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/wtxpwh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
